#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
gnome-terminal -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
chromium --user-data-dir=~/.config/chromium/Profile\ 1&
fluxbox
