#!/bin/bash

read -d '' send_notification << 'EOF'
if $_ =~ /<([^>]+)>(.*)/
  `notify-send -t 3000 #{$1.shellescape} #{$2.shellescape}`
end
EOF
year=$(date "+%Y")
day=$(date "+%m-%d")
tail -q -n0 -f "$HOME/.irssi/logs/$year/$day/"*/*.log | ruby -rshellwords -ne "$send_notification" &
