#!/bin/bash

session="sharktank"
socket="/tmp/$session-s"

pushd "$HOME/work/sales"
tmux -S "$socket" new-session -s "$session" -d
tmux -S "$socket" new-window -t "$session"
tmux -S "$socket" new-window -t "$session"
TERM=screen-256color tmux -2 -S "$socket" attach-session -t "$session"
