(deftheme agnostic
  "Created 2015-04-22.")

(custom-theme-set-faces
 'agnostic
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "brightred"))))
 '(minibuffer-prompt ((t (:foreground "brightgreen"))))
 '(highlight ((t (:background "brightblack"))))
 '(region ((t (:background "brightblack"))))
 '(shadow ((t (:foreground "white"))))
 '(secondary-selection ((t (:background "cyan" :foreground "brightwhite"))))
 '(trailing-whitespace ((t (:background "brightred"))))
 '(font-lock-builtin-face ((t (:foreground "brightred" :weight bold))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "blue"))))
 '(font-lock-constant-face ((t (:foreground "brightcyan" :weight bold))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "brightred" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "brightmagenta" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "brightcyan"))))
 '(font-lock-type-face ((t (:foreground "brightyellow"))))
 '(font-lock-variable-name-face ((t (:foreground "brightblue"))))
 '(font-lock-warning-face ((t (:background "yellow" :foreground "brightwhite" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "brightmagenta" :underline t))))
 '(link-visited ((t (:inherit link :foreground "brightblue"))))
 '(fringe ((t (:background "grey10"))))
 '(header-line ((t (:background "cyan" :foreground "brightwhite" :weight bold))))
 '(tooltip ((t (:inherit variable-pitch :background "yellow" :foreground "white"))))
 '(mode-line ((t (:background "cyan" :foreground "brightwhite" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "white" :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :background "brightblue" :foreground "black" :box (:line-width -1 :color "white") :weight light))))
 '(isearch ((t (:background "yellow" :foreground "brightwhite"))))
 '(isearch-fail ((t (:background "red"))))
 '(lazy-highlight ((t (:background "cyan"))))
 '(match ((t (:background "cyan" :foreground "brightwhite"))))
 '(next-error ((t (:inherit region))))
 '(query-replace ((t (:inherit isearch))))
 '(default ((t (:inherit nil :stipple nil :background "unspecified-bg" :foreground "brightwhite" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
 '(linum ((t (:background "brightblue" :foreground "black")))))

(provide-theme 'agnostic)
